baseURL = "/"
languageCode = "en-us"
title = "VMware Operations Guide"
theme = "hugo-theme-clarity-learn"
enableGitInfo = true

# defaultContentLanguage = "en" # English is the default language
defaultContentLanguageInSubdir = false # Force to have /en/my-page and /fr/my-page routes, even for default language.
disableLanguages = [""]

[Languages]
  [Languages.en]
    title = "VMware Operations Guide"
    weight = 1
    languageName = "English"

  [Languages.zh]
    title = "VMware 操作指南"
    weight = 2
    languageName = "Chinese (Simplified)"

  [Languages.zh-tw]
    title = "VMware 操作指南"
    weight = 2
    languageName = "Chinese (Traditional)"

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[params]
  editURL = "https://github.com/TheNewStellW/vmware-operations-guide/tree/main/content/"
<<<<<<< HEAD
  disableReadingTime = false
=======

[[menu.shortcuts]]
  name = "Iwan 'e1' Rahabok"
  identifier = "ds"
  url = "http://virtual-red-dot.info/iwan-rahabok/"
  weight = 10
>>>>>>> 782d05a (add clarity theme)

[[menu.shortcuts]]
  name = "Hosted on FunkyCloudMedina"
  identifier = "fcm"
  url = "https://www.funkycloudmedina.com/"
  weight = 15

[[menu.shortcuts]] 
  name = "Learn Code Stream"
  identifier = "lcm"
  url = "https://learncodestream.github.io/"
  weight = 30

[[menu.shortcuts]] 
  name = "Learn Cloud Assembly"
  identifier = "lca"
  url = "https://learncloudassembly.github.io/"
  weight = 20

[[menu.shortcuts]] 
  name = "Learn Service Broker"
  identifier = "lsb"
  url = "https://learnservicebroker.github.io/"
  weight = 25

[[menu.shortcuts]] 
  name = "Learn Salt Stack"
  identifier = "lss"
  url = "https://learnsaltstackconfig.github.io/"
  weight = 35

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
